#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Config

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config focus_follows_pointer true
bspc config presel_feedback_color "$color1"

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Connect monitors
start_from=1
monitors_connected=$(bspc query -M | wc -l)
per_monitor=$(( 10 / monitors_connected ))
for monitor in $(bspc query -M); do
   bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor - 1)))
   start_from=$(( start_from + per_monitor ))
done

# Update monitor info
xrandr --auto
# Setup monitor layout
sh ~/.screenlayout/normal-1-1.sh

# Set the default X cursor to the usual pointer
xsetroot -cursor_name left_ptr

# Set a nice background
feh --bg-fill --no-fehbg ~/Pictures/Wallpapers/penguin.jpg &

# Change color pallete based on the background
wal -i ~/Pictures/Wallpapers/penguin.jpg -s &

# Set keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ru &

# Set picom
picom -C --config ~/.config/picom.conf &

# Power Management
xfce4-power-manager &

# Kill running polybars
killall -q polybar

# Setup polybars 
while pgrep -x polybar >/dev/null; do 
  sleep 1;
done
xrandr -q | awk '/ connected / {print $1}' | while read -r monitor _; do
  polybar -r $monitor &
done

# Rules
bspc config remove_unplugged_monitors true
bspc rule -a Gnome-Terminal desktop='^1' follow=on focus=on
bspc rule -a brave desktop='^2'follow=on focus=on
bspc rule -a telegram-desktop desktop='^3'follow=on focus=on
bspc rule -a code desktop='^6' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
